import type {
  ChapterStructureConfig,
  DependencyImpact,
  LearnerProgressPolicy,
  ProgramPhaseLabel,
} from "@/lib/v2/types/domain";

export const CALM_COMMERCE_PHASES: Record<number, ProgramPhaseLabel> = {
  1: "Get Started",
  2: "Set Your Rules and Test",
  3: "Build Your Offer",
  4: "Get Your Store Ready",
  5: "Get Customers",
  6: "Measure, Learn, Grow",
  7: "Ongoing Operations",
};

export const CALM_COMMERCE_PROGRESS_POLICY: LearnerProgressPolicy = {
  navigation: "hybrid_locked_progression",
  chapterCompletion: "viewed_final_step_and_required_worksheet",
  chapter17Completion: "dashboard_view",
  downstreamUpdates: "warn_then_confirm",
  pivotHistory: "background_version_history",
};

export const CALM_COMMERCE_STEP_CONFIG: ChapterStructureConfig[] = [
  {
    chapterId: "chapter-1",
    chapterSlug: "welcome-you-can-do-this",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-1-step-1", label: "You are about to build something real", sectionRange: ["1.1"] },
      { id: "chapter-1-step-2", label: "What this course is", sectionRange: ["1.2"] },
      { id: "chapter-1-step-3", label: "How the course works", sectionRange: ["1.3"] },
      { id: "chapter-1-step-4", label: "What you will need", sectionRange: ["1.4"] },
    ],
  },
  {
    chapterId: "chapter-2",
    chapterSlug: "choose-how-youll-sell",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-2-step-1", label: "The question before the question", sectionRange: ["2.1"] },
      { id: "chapter-2-step-2", label: "Models 1 to 3", sectionRange: ["2.2.1", "2.2.2", "2.2.3"] },
      { id: "chapter-2-step-3", label: "Models 4 to 5 and flexibility", sectionRange: ["2.2.4", "2.2.5", "2.3"] },
      { id: "chapter-2-step-4", label: "Before you move on", sectionRange: ["2.4"] },
    ],
  },
  {
    chapterId: "chapter-3",
    chapterSlug: "brainstorm-with-discipline",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-3-step-1", label: "Where good ideas come from", sectionRange: ["3.1", "3.2"] },
      { id: "chapter-3-step-2", label: "Search and review signals", sectionRange: ["3.3", "3.4"] },
      { id: "chapter-3-step-3", label: "Listen for unmet needs", sectionRange: ["3.5", "3.6"] },
      { id: "chapter-3-step-4", label: "Competition and scoring", sectionRange: ["3.7", "3.8", "3.9"] },
      { id: "chapter-3-step-5", label: "You are making real progress", sectionRange: ["3.10"] },
    ],
  },
  {
    chapterId: "chapter-4",
    chapterSlug: "set-your-founder-rules",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-4-step-1", label: "Your ideas deserve protection", sectionRange: ["4.1"] },
      { id: "chapter-4-step-2", label: "Time rules", sectionRange: ["4.2"] },
      { id: "chapter-4-step-3", label: "Money rules", sectionRange: ["4.3"] },
      { id: "chapter-4-step-4", label: "Decision rules and data", sectionRange: ["4.4", "4.5"] },
      { id: "chapter-4-step-5", label: "Red lines and operating system", sectionRange: ["4.6", "4.7"] },
    ],
  },
  {
    chapterId: "chapter-5",
    chapterSlug: "know-your-numbers-before-you-commit",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-5-step-1", label: "Maths and why it matters", sectionRange: ["5.1", "5.2"] },
      { id: "chapter-5-step-2", label: "Costs and shipping", sectionRange: ["5.3", "5.4"] },
      { id: "chapter-5-step-3", label: "Complexity and suppliers", sectionRange: ["5.5", "5.6"] },
      { id: "chapter-5-step-4", label: "Score your ideas", sectionRange: ["5.7"] },
      { id: "chapter-5-step-5", label: "Choose the viable idea", sectionRange: ["5.8"] },
    ],
  },
  {
    chapterId: "chapter-6",
    chapterSlug: "test-before-you-build-a-store",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-6-step-1", label: "Why marketplaces first", sectionRange: ["6.1", "6.2"] },
      { id: "chapter-6-step-2", label: "Choose and write the listing", sectionRange: ["6.3", "6.4"] },
      { id: "chapter-6-step-3", label: "Set duration and ship well", sectionRange: ["6.5", "6.6"] },
      { id: "chapter-6-step-4", label: "Read results and decide", sectionRange: ["6.7", "6.8"] },
      { id: "chapter-6-step-5", label: "What this test proves", sectionRange: ["6.9"] },
    ],
  },
  {
    chapterId: "chapter-7",
    chapterSlug: "pick-your-customer",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-7-step-1", label: "Why everyone is not the customer", sectionRange: ["7.1", "7.2"] },
      { id: "chapter-7-step-2", label: "Define your niche customer", sectionRange: ["7.3"] },
      { id: "chapter-7-step-3", label: "Find where they gather", sectionRange: ["7.4"] },
      { id: "chapter-7-step-4", label: "Value and trust", sectionRange: ["7.5", "7.6"] },
      { id: "chapter-7-step-5", label: "You now know who you are talking to", sectionRange: ["7.7"] },
    ],
  },
  {
    chapterId: "chapter-8",
    chapterSlug: "shape-your-offer",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-8-step-1", label: "A product is not an offer", sectionRange: ["8.1", "8.2"] },
      { id: "chapter-8-step-2", label: "Positioning and minimum offer", sectionRange: ["8.3", "8.4"] },
      { id: "chapter-8-step-3", label: "Name and price", sectionRange: ["8.5", "8.6"] },
      { id: "chapter-8-step-4", label: "Margin check", sectionRange: ["8.7"] },
      { id: "chapter-8-step-5", label: "Your offer is ready", sectionRange: ["8.8"] },
    ],
  },
  {
    chapterId: "chapter-9",
    chapterSlug: "write-listings-that-sell",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-9-step-1", label: "Your listing is your salesperson", sectionRange: ["9.1", "9.2"] },
      { id: "chapter-9-step-2", label: "Write the description", sectionRange: ["9.3"] },
      { id: "chapter-9-step-3", label: "Take photos that build confidence", sectionRange: ["9.4"] },
      { id: "chapter-9-step-4", label: "Social proof from zero", sectionRange: ["9.5"] },
      { id: "chapter-9-step-5", label: "Your listing is ready", sectionRange: ["9.6"] },
    ],
  },
  {
    chapterId: "chapter-10",
    chapterSlug: "what-your-store-actually-needs",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-10-step-1", label: "It is simpler than you think", sectionRange: ["10.1", "10.2"] },
      { id: "chapter-10-step-2", label: "The essential building blocks", sectionRange: ["10.3"] },
      { id: "chapter-10-step-3", label: "Payments, legal, and checkout", sectionRange: ["10.4", "10.5"] },
      { id: "chapter-10-step-4", label: "What ready actually means", sectionRange: ["10.6", "10.7", "10.8"] },
    ],
  },
  {
    chapterId: "chapter-11",
    chapterSlug: "free-traffic-start-without-spending",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-11-step-1", label: "Your store is open", sectionRange: ["11.1"] },
      { id: "chapter-11-step-2", label: "Share in communities", sectionRange: ["11.2"] },
      { id: "chapter-11-step-3", label: "Basic SEO", sectionRange: ["11.3"] },
      { id: "chapter-11-step-4", label: "Social and personal network", sectionRange: ["11.4", "11.5"] },
      { id: "chapter-11-step-5", label: "Track what is working", sectionRange: ["11.6", "11.7", "11.8"] },
    ],
  },
  {
    chapterId: "chapter-12",
    chapterSlug: "paid-ads-small-budget-testing",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-12-step-1", label: "How paid ads work", sectionRange: ["12.1", "12.2"] },
      { id: "chapter-12-step-2", label: "Set up your first test", sectionRange: ["12.3"] },
      { id: "chapter-12-step-3", label: "The numbers that matter", sectionRange: ["12.4"] },
      { id: "chapter-12-step-4", label: "Read results and update rules", sectionRange: ["12.5", "12.6"] },
      { id: "chapter-12-step-5", label: "Mistakes and momentum", sectionRange: ["12.7", "12.8"] },
    ],
  },
  {
    chapterId: "chapter-13",
    chapterSlug: "email-and-repeat-customers",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-13-step-1", label: "Why email matters", sectionRange: ["13.1", "13.2"] },
      { id: "chapter-13-step-2", label: "Collect emails", sectionRange: ["13.3"] },
      { id: "chapter-13-step-3", label: "Your first three emails", sectionRange: ["13.4"] },
      { id: "chapter-13-step-4", label: "Post-purchase and LTV", sectionRange: ["13.5", "13.6"] },
      { id: "chapter-13-step-5", label: "You now have three engines", sectionRange: ["13.7"] },
    ],
  },
  {
    chapterId: "chapter-14",
    chapterSlug: "weekly-review-and-decision-rhythm",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-14-step-1", label: "Your six numbers", sectionRange: ["14.1", "14.2"] },
      { id: "chapter-14-step-2", label: "Where to find them", sectionRange: ["14.3", "14.4"] },
      { id: "chapter-14-step-3", label: "The weekly review ritual", sectionRange: ["14.5"] },
      { id: "chapter-14-step-4", label: "Update rules and act", sectionRange: ["14.6", "14.7"] },
    ],
  },
  {
    chapterId: "chapter-15",
    chapterSlug: "iterate-double-down-or-pivot",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-15-step-1", label: "What problem are you solving now", sectionRange: ["15.1"] },
      { id: "chapter-15-step-2", label: "Diagnose the issue", sectionRange: ["15.2"] },
      { id: "chapter-15-step-3", label: "Iterate what can improve", sectionRange: ["15.3"] },
      { id: "chapter-15-step-4", label: "When to pivot", sectionRange: ["15.4"] },
      { id: "chapter-15-step-5", label: "When not to pivot", sectionRange: ["15.5", "15.6"] },
    ],
  },
  {
    chapterId: "chapter-16",
    chapterSlug: "grow-without-breaking-what-works",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-16-step-1", label: "Recognise what is working", sectionRange: ["16.1", "16.2"] },
      { id: "chapter-16-step-2", label: "Scale carefully", sectionRange: ["16.3"] },
      { id: "chapter-16-step-3", label: "Add products or a second store", sectionRange: ["16.4", "16.5"] },
      { id: "chapter-16-step-4", label: "Update your rules", sectionRange: ["16.6"] },
      { id: "chapter-16-step-5", label: "Growth with control", sectionRange: ["16.7"] },
    ],
  },
  {
    chapterId: "chapter-17",
    chapterSlug: "run-the-business-like-a-real-operator",
    allowRevisitAfterCompletion: true,
    progression: "sequential_locked",
    worksheetPlacement: { strategy: "penultimateTeachingStep", excludeClosingStep: true },
    stepBreaks: [
      { id: "chapter-17-step-1", label: "Weekly review", sectionRange: ["17.1"] },
      { id: "chapter-17-step-2", label: "What to review", sectionRange: ["17.2"] },
      { id: "chapter-17-step-3", label: "Entering and reading metrics", sectionRange: ["17.3"] },
      { id: "chapter-17-step-4", label: "What happens next", sectionRange: ["17.4"] },
    ],
  },
];

export const CALM_COMMERCE_DEPENDENCY_RULES: DependencyImpact[] = [
  {
    sourceFieldKey: "product_ideas",
    affectedFieldKeys: ["chosen_idea", "test_idea", "offer_name", "offer_positioning"],
    affectedCanvasSections: ["product_candidates", "product_economics", "value_proposition"],
    warningMessage:
      "Changing or deleting a product idea can break your chosen idea, offer setup, and later canvas sections.",
    suggestedActionLabel: "Review affected idea references",
  },
  {
    sourceFieldKey: "chosen_idea",
    affectedFieldKeys: ["test_idea", "offer_name", "offer_positioning", "listing_title"],
    affectedCanvasSections: ["product_economics", "solution", "value_proposition"],
    warningMessage:
      "Changing the chosen idea will affect offer, listing, and economics work that depends on it.",
    suggestedActionLabel: "Update downstream idea-dependent content",
  },
  {
    sourceFieldKey: "money_cap_per_month",
    affectedFieldKeys: ["estimated_startup_cost", "ad_test_budget"],
    affectedCanvasSections: ["operating_constraints", "product_economics", "channels_paid"],
    warningMessage:
      "Updating your money cap can change whether later sourcing, economics, and paid-testing decisions still fit.",
    suggestedActionLabel: "Recheck budget-dependent decisions",
  },
  {
    sourceFieldKey: "time_budget_hours_per_week",
    affectedFieldKeys: ["posting_frequency", "ad_management_time"],
    affectedCanvasSections: ["operating_constraints", "channels_free", "channels_paid"],
    warningMessage:
      "Updating your time budget can invalidate later traffic and growth commitments.",
    suggestedActionLabel: "Review time-dependent plans",
  },
];

export const CALM_COMMERCE_CROSS_CHECK_RULE_KEYS = [
  "budget-vs-startup-cost",
  "stock-investment-vs-budget",
  "margin-viability",
  "cpa-vs-margin",
  "cpa-vs-ltv",
  "time-budget-vs-channels",
  "store-readiness-gate",
] as const;
